SMIBHID has a webserver! Closes #248
somakeit/smib pull request #249
Opened 2024-10-14 19:20 UTC by sjefferson99

2024-10-14 20:16 UTC, sam57719 requested changes
Code is massive and looks OK, apart from some PEP8 naming convention violations.

I want to test this myself on my own SMIBHID dev board. Probably wont happen until tomorrow or Wednesday.

2024-10-14 20:16 UTC, sam57719 commented on smibhid/http/website.py
> +class Web_App:
PEP8 naming violation - should be `WebApp`

2024-10-14 20:16 UTC, sam57719 commented on smibhid/http/website.py
> +class wlan_mac():
again - should be PEP8

2024-10-14 20:16 UTC, sam57719 commented on smibhid/http/website.py
> +class version():
PEP8

2024-10-14 20:16 UTC, sam57719 commented on smibhid/http/webserver.py
> +class request:
PEP8

2024-10-14 20:16 UTC, sam57719 commented on smibhid/http/webserver.py
> +class response:
PEP8

2024-10-14 20:16 UTC, sam57719 commented on smibhid/http/webserver.py
> +class webserver:
PEP8

2024-10-14 20:33 UTC, sjefferson99 commented
PEP8 issues adjusted. The webserver module is not mine, but I have adjusted enough of it already to take on and continue adjusting things like class names and have adjusted these as well.

2024-10-14 20:34 UTC, sam57719 reviewed
Happy with the PEP8 changes

2024-10-14 20:35 UTC, sam57719 commented
@sjefferson99 I want to test this tomorrow/Wednesday before I approve

2024-10-23 19:58 UTC, sam57719 commented
There is a merge conflict - please sort it :) @sjefferson99

2024-10-23 21:15 UTC, sam57719 approved these changes
Tell my WiFi love her

2024-10-23 21:15 UTC, merged